spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.27:3306/num3?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123
  # redis 配置
  redis:
    host: 192.168.216.128
    port: 6379
#    日志配置
logging:
  level:
    com.shangma: debug
  file:
    name: E:/workspace/project3/log/mylog.log

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.shangma.entity
  global-config:
    banner: false
  type-enums-package: com.shangma.enums
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
